export const BLOG_POSTS = [
  {
    id: 1,
    slug: "how-to-improve-chess-rating",
    category: "Training",
    title: "How to Improve Chess Rating",
    desc: "A step-by-step roadmap to breaking through your ELO plateau and climbing the competitive ranks.",
    date: "Feb 24, 2024",
    author: "Raghava M.",
    image: "/1.webp",
    color: "bg-white",
    shadow: "shadow-[8px_8px_0px_0px_rgba(253,224,71,1)]"
  },
  {
    id: 2,
    slug: "best-openings-for-beginners",
    category: "Openings",
    title: "Best Openings for Beginners",
    desc: "Stop memorizing theory. Learn the top 3 opening systems that prioritize development and safety.",
    date: "Feb 22, 2024",
    author: "Admin",
    image: "/2.webp",
    color: "bg-yellow-400",
    shadow: "shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]"
  },
  {
    id: 3,
    slug: "how-to-prepare-for-tournaments",
    category: "Prep",
    title: "How to Prepare for Tournaments",
    desc: "A complete guide on physical stamina, mental prep, and analyzing your opponents before a big event.",
    date: "Feb 20, 2024",
    author: "Raghava M.",
    image: "/3.avif",
    color: "bg-black",
    textColor: "text-white",
    shadow: "shadow-[8px_8px_0px_0px_rgba(253,224,71,1)]"
  },
  {
    id: 4,
    slug: "common-chess-mistakes",
    category: "Analysis",
    title: "Common Chess Mistakes",
    desc: "Identify the recurring blunders that cost most amateur players their games and how to fix them.",
    date: "Feb 18, 2024",
    author: "Admin",
    image: "/4.webp",
    color: "bg-white",
    shadow: "shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]"
  },
  {
    id: 5,
    slug: "the-sicilian-defense-masterclass",
    category: "Strategy",
    title: "The Sicilian Defense: A Modern Masterclass",
    desc: "Why the Sicilian remains the most popular response to 1.e4 and how you can master its complexities.",
    date: "Feb 12, 2024",
    author: "Raghava M.",
    image: "/5.avif",
    color: "bg-white",
    shadow: "shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]"
  },
  {
    id: 6,
    slug: "why-chess-secret-to-focus-kids",
    category: "Cognitive",
    title: "Why Chess is the Secret to Focus in Kids",
    desc: "Scientific insights into how the 64 squares help children build extreme concentration and patience.",
    date: "Feb 10, 2024",
    author: "Admin",
    image: "/6.jpg",
    color: "bg-yellow-400",
    shadow: "shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]"
  },
  {
    id: 7,
    slug: "tournament-nerves-psychology",
    category: "Mindset",
    title: "Tournament Nerves: Staying Calm Under Pressure",
    desc: "Elite psychological techniques to handle high-stakes games and avoid 'Chess Blindness'.",
    date: "Feb 08, 2024",
    author: "Raghava M.",
    image: "/7.webp",
    color: "bg-black",
    textColor: "text-white",
    shadow: "shadow-[8px_8px_0px_0px_rgba(253,224,71,1)]"
  },
  {
    id: 8,
    slug: "endgame-precision-guide",
    category: "Tactical",
    title: "Endgame Precision: Converting the Advantage",
    desc: "Don't let a winning position slip. Learn the essential pawn endings every master must know.",
    date: "Feb 05, 2024",
    author: "Admin",
    image: "/8.webp",
    color: "bg-white",
    shadow: "shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]"
  },
  {
    id: 9,
    slug: "online-vs-offline-chess",
    category: "Training",
    title: "Online vs Offline: The Digital Evolution",
    desc: "How engine analysis and global platforms are creating the youngest Grandmasters in history.",
    date: "Feb 01, 2024",
    author: "Raghava M.",
    image: "/9.jpg",
    color: "bg-white",
    shadow: "shadow-[8px_8px_0px_0px_rgba(253,224,71,1)]"
  },
  {
    id: 10,
    slug: "chess-and-math-connection",
    category: "Education",
    title: "Chess and Math: The Invisible Connection",
    desc: "Exploring the geometry of the board and how spatial reasoning helps with advanced mathematics.",
    date: "Jan 28, 2024",
    author: "Admin",
    image: "/10.jpg",
    color: "bg-yellow-400",
    shadow: "shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]"
  },
  {
    id: 11,
    slug: "history-of-chess-evolution",
    category: "Culture",
    title: "The History of Chess: From Chaturanga to AI",
    desc: "A journey through 1,500 years of evolution that led to the modern game we love today.",
    date: "Jan 25, 2024",
    author: "Admin",
    image: "/11.jpg",
    color: "bg-black",
    textColor: "text-white",
    shadow: "shadow-[8px_8px_0px_0px_rgba(253,224,71,1)]"
  },
  {
    id: 12,
    slug: "prepare-first-fide-tournament",
    category: "Prep",
    title: "How to Prepare for Your First FIDE Tournament",
    desc: "A complete checklist for parents and students entering the world of rated competitive chess.",
    date: "Jan 20, 2024",
    author: "Raghava M.",
    image: "/12.avif",
    color: "bg-white",
    shadow: "shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]"
  }
];